### ISSUE TITLE
Zonotopes as inputs with refinezono

### ISSUE THREAD

**Issue by antoniobruto** [eth-sri/eran#12]
Dear Gagandeep,

We made the following invocation of ERAN:
python3 . --netname ../nets/mnist_relu_6_100.tf --domain refinezono --zonotope ../nets/zonotope_example.txt --dataset mnist

We tried with both examples you provided for zonotopes with refinezono. It seems that there is an error when using refinezono. So far, we haven't found any issues with deepzono.

The traceback of the issue is below:
**Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 309, in <module>
    perturbed_label, nn, nlb, nub = eran.analyze_zonotope(zonotope, domain, args.timeout_lp, args.timeout_milp, args.use_area_heuristic)
  File "./eran.py", line 111, in analyze_zonotope
    dominant_class, nlb, nub = analyzer.analyze()
  File "./analyzer.py", line 100, in analyze
    element, nlb, nub = self.get_abstract0()
  File "./analyzer.py", line 85, in get_abstract0
    element = self.ir_list[i].transformer(self.nn, self.man, element, nlb,nub, self.domain=='refinezono', self.timeout_lp, self.timeout_milp)
  File "./deepzono_nodes.py", line 728, in transformer
    element = refine_relu_with_solver_bounds(nn, self, man, element, nlb, nub, timeout_lp, timeout_milp)
  File "./deepzono_nodes.py", line 170, in refine_relu_with_solver_bounds
    resl, resu, indices = get_bounds_for_layer_with_milp(nn, nn.specLB, nn.specUB, layerno, layerno, length, nlb, nub, use_milp,  candidate_vars, timeout)
  File "./deepzono_milp.py", line 424, in get_bounds_for_layer_with_milp
    counter, var_list, model = create_model(nn, LB_N0, UB_N0, nlb, nub, layerno+1, use_milp, relu_needed)
  File "./deepzono_milp.py", line 317, in create_model
    counter = handle_affine(model,var_list,counter,weights,biases,nlb[i],nub[i])
  File "./deepzono_milp.py", line 168, in handle_affine
    expr.addTerms(weights[j][k],var_list[counter+k])
IndexError: list index out of range**

Any ideas?

Regards,
Antonio

**Comment by GgnDpSngh** [comment]
Hi Antonio,

Thanks for pointing this out, I have added support for handling Zonotope specs with Refinezono and now you should not get this error.  Let me know if you encounter any bugs.

Cheers,
Gagandeep Singh
