### ISSUE TITLE
TypeError: __int__ returned non-int (type NoneType)

### ISSUE THREAD

**Issue by LebronX** [eth-sri/eran#81]
Hi,

I try to use run eran on a pb file ( as attached:
[mnist_fc.zip](https://github.com/eth-sri/eran/files/6561766/mnist_fc.zip)
) with tensorflow version 1.14.0, and eran report the following error

error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 471, in <module>
    eran = ERAN(model, sess)
  File "./eran.py", line 53, in __init__
    operations, resources = translator.translate()
  File "./tensorflow_translator.py", line 178, in translate
    in_out_info = (input_tensor_names, op.outputs[0].name, tensorshape_to_intlist(op.outputs[0].shape))
  File "./tensorflow_translator.py", line 44, in tensorshape_to_intlist
    return list(map(lambda j: 1 if j is None else int(j), tensorshape))
  File "./tensorflow_translator.py", line 44, in <lambda>
    return list(map(lambda j: 1 if j is None else int(j), tensorshape))
TypeError: __int__ returned non-int (type NoneType)
```

command: 
```
python3 . --netname ./mnist_fc.pb --epsilon 0.1 --domain deepzono --dataset mnist
```

Thanks

**Comment by mnmueller** [comment]
Hello @LebronX,

Thank you for your interest in ERAN. 
We are focusing on supporting the ".onnx" format for networks.
Please try to translate your network using a tool such as tf2onnx (https://github.com/onnx/tensorflow-onnx) to onnx format before  using ERAN,

Cheers,
Mark
